// ---
CREATE TABLE public.homework (
	id          int4        NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
	"name"      text        NOT NULL,
	description text        NULL,
	CONSTRAINT  homework_pk PRIMARY KEY (id)
);

// ---
CREATE TABLE public.lesson (
	id          int4        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name"      varchar     NOT NULL,
	updateat    date        NULL,
	homework_id int4        NULL,
	CONSTRAINT  lesson_pk   PRIMARY KEY (id),
	CONSTRAINT  lesson_fk   FOREIGN KEY (homework_id) REFERENCES public.homework(id)
);

// ---
CREATE TABLE public.schedule (
	id          int4        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name"      varchar     NOT NULL,
	updateat    date        NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT  schedule_pk PRIMARY KEY (id)
);

// ---
CREATE TABLE public.lessonshedule (
	id          int4        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	lesson_id   int4        NULL,
	schedule_id int4        NULL,
	CONSTRAINT  lessonshedule_pk PRIMARY KEY (id),
	CONSTRAINT  lessonshedule_fk FOREIGN KEY (lesson_id) REFERENCES public.lesson(id),
	CONSTRAINT  lessonshedule_fk_1 FOREIGN KEY (schedule_id) REFERENCES public.schedule(id)
);