ALTER TABLE persons ADD COLUMN IF NOT EXISTS uid VARCHAR(40);
ALTER TABLE persons ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE persons ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE persons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;