CREATE TABLE IF NOT EXISTS accounts
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid  VARCHAR(40),
    iban VARCHAR(40),
    balance INTEGER,
    person_id INTEGER,
    CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES persons (id)
);